#include "window_theme.h"

void Nexus::WindowTheme::UpdateColor(ImVec4 *colors)
{
    /*******************************
     * THEMES WERE GENERATED BY AI *
     *******************************/
    // Atom One Dark color theme
    colors[ImGuiCol_Text] = ImVec4(0.75f, 0.80f, 0.85f, 1.00f);
    colors[ImGuiCol_TextDisabled] = ImVec4(0.38f, 0.41f, 0.45f, 1.00f);
    colors[ImGuiCol_WindowBg] = ImVec4(0.10f, 0.12f, 0.14f, 1.00f);
    colors[ImGuiCol_ChildBg] = ImVec4(0.12f, 0.14f, 0.16f, 1.00f);
    colors[ImGuiCol_PopupBg] = ImVec4(0.13f, 0.15f, 0.18f, 1.00f);
    colors[ImGuiCol_Border] = ImVec4(0.18f, 0.20f, 0.22f, 1.00f);
    colors[ImGuiCol_BorderShadow] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
    colors[ImGuiCol_FrameBg] = ImVec4(0.16f, 0.18f, 0.22f, 1.00f);
    colors[ImGuiCol_FrameBgHovered] = ImVec4(0.20f, 0.22f, 0.26f, 1.00f);
    colors[ImGuiCol_FrameBgActive] = ImVec4(0.22f, 0.24f, 0.28f, 1.00f);
    colors[ImGuiCol_TitleBg] = ImVec4(0.09f, 0.10f, 0.12f, 1.00f);
    colors[ImGuiCol_TitleBgActive] = ImVec4(0.13f, 0.15f, 0.17f, 1.00f);
    colors[ImGuiCol_TitleBgCollapsed] = ImVec4(0.07f, 0.08f, 0.09f, 1.00f);
    colors[ImGuiCol_MenuBarBg] = ImVec4(0.13f, 0.15f, 0.18f, 1.00f);
    colors[ImGuiCol_ScrollbarBg] = ImVec4(0.09f, 0.10f, 0.12f, 1.00f);
    colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.22f, 0.24f, 0.28f, 1.00f);
    colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(0.28f, 0.30f, 0.34f, 1.00f);
    colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.34f, 0.36f, 0.40f, 1.00f);
    colors[ImGuiCol_CheckMark] = ImVec4(0.46f, 0.77f, 0.55f, 1.00f);
    colors[ImGuiCol_SliderGrab] = ImVec4(0.30f, 0.50f, 0.85f, 1.00f);
    colors[ImGuiCol_SliderGrabActive] = ImVec4(0.40f, 0.60f, 1.00f, 1.00f);
    colors[ImGuiCol_Button] = ImVec4(0.18f, 0.22f, 0.28f, 1.00f);
    colors[ImGuiCol_ButtonHovered] = ImVec4(0.24f, 0.28f, 0.34f, 1.00f);
    colors[ImGuiCol_ButtonActive] = ImVec4(0.28f, 0.32f, 0.38f, 1.00f);
    colors[ImGuiCol_Header] = ImVec4(0.18f, 0.22f, 0.28f, 1.00f);
    colors[ImGuiCol_HeaderHovered] = ImVec4(0.24f, 0.28f, 0.34f, 1.00f);
    colors[ImGuiCol_HeaderActive] = ImVec4(0.28f, 0.32f, 0.38f, 1.00f);
    colors[ImGuiCol_Separator] = ImVec4(0.18f, 0.20f, 0.22f, 1.00f);
    colors[ImGuiCol_SeparatorHovered] = ImVec4(0.30f, 0.32f, 0.36f, 1.00f);
    colors[ImGuiCol_SeparatorActive] = ImVec4(0.40f, 0.42f, 0.46f, 1.00f);
    colors[ImGuiCol_ResizeGrip] = ImVec4(0.22f, 0.40f, 0.65f, 1.00f);
    colors[ImGuiCol_ResizeGripHovered] = ImVec4(0.32f, 0.50f, 0.75f, 1.00f);
    colors[ImGuiCol_ResizeGripActive] = ImVec4(0.42f, 0.70f, 0.95f, 1.00f);
    colors[ImGuiCol_InputTextCursor] = ImVec4(0.85f, 0.85f, 0.85f, 1.00f);
    colors[ImGuiCol_TabHovered] = ImVec4(0.22f, 0.28f, 0.38f, 1.00f);
    colors[ImGuiCol_Tab] = ImVec4(0.13f, 0.16f, 0.22f, 1.00f);
    colors[ImGuiCol_TabSelected] = ImVec4(0.18f, 0.22f, 0.28f, 1.00f);
    colors[ImGuiCol_TabSelectedOverline] = ImVec4(0.55f, 0.62f, 0.90f, 1.00f);
    colors[ImGuiCol_TabDimmed] = ImVec4(0.10f, 0.12f, 0.16f, 1.00f);
    colors[ImGuiCol_TabDimmedSelected] = ImVec4(0.16f, 0.18f, 0.22f, 1.00f);
    colors[ImGuiCol_TabDimmedSelectedOverline] = ImVec4(0.30f, 0.38f, 0.75f, 1.00f);
    colors[ImGuiCol_DockingPreview] = ImVec4(0.20f, 0.45f, 0.80f, 0.35f);
    colors[ImGuiCol_DockingEmptyBg] = ImVec4(0.10f, 0.12f, 0.14f, 1.00f);
    colors[ImGuiCol_PlotLines] = ImVec4(0.40f, 0.45f, 0.50f, 1.00f);
    colors[ImGuiCol_PlotLinesHovered] = ImVec4(0.90f, 0.33f, 0.25f, 1.00f);
    colors[ImGuiCol_PlotHistogram] = ImVec4(0.88f, 0.67f, 0.23f, 1.00f);
    colors[ImGuiCol_PlotHistogramHovered] = ImVec4(0.90f, 0.50f, 0.10f, 1.00f);
    colors[ImGuiCol_TableHeaderBg] = ImVec4(0.13f, 0.16f, 0.22f, 1.00f);
    colors[ImGuiCol_TableBorderStrong] = ImVec4(0.18f, 0.20f, 0.22f, 1.00f);
    colors[ImGuiCol_TableBorderLight] = ImVec4(0.13f, 0.16f, 0.18f, 1.00f);
    colors[ImGuiCol_TableRowBg] = ImVec4(0.10f, 0.12f, 0.14f, 1.00f);
    colors[ImGuiCol_TableRowBgAlt] = ImVec4(0.12f, 0.14f, 0.16f, 1.00f);
    colors[ImGuiCol_TextLink] = ImVec4(0.41f, 0.61f, 0.85f, 1.00f);
    colors[ImGuiCol_TextSelectedBg] = ImVec4(0.20f, 0.40f, 0.65f, 0.70f);
    colors[ImGuiCol_TreeLines] = ImVec4(0.18f, 0.20f, 0.22f, 1.00f);
    colors[ImGuiCol_DragDropTarget] = ImVec4(0.90f, 0.80f, 0.20f, 0.90f);
    colors[ImGuiCol_NavCursor] = ImVec4(0.80f, 0.70f, 0.30f, 1.00f);
    colors[ImGuiCol_NavWindowingHighlight] = ImVec4(0.55f, 0.60f, 0.65f, 0.70f);
    colors[ImGuiCol_NavWindowingDimBg] = ImVec4(0.10f, 0.10f, 0.14f, 0.60f);
    colors[ImGuiCol_ModalWindowDimBg] = ImVec4(0.06f, 0.07f, 0.08f, 0.70f);

    // NOTE: For easy copy-paste into a prompt
    // colors[ImGuiCol_Text] = ImVec4();
    // colors[ImGuiCol_TextDisabled] = ImVec4();
    // colors[ImGuiCol_WindowBg] = ImVec4();
    // colors[ImGuiCol_ChildBg] = ImVec4();
    // colors[ImGuiCol_PopupBg] = ImVec4();
    // colors[ImGuiCol_Border] = ImVec4();
    // colors[ImGuiCol_BorderShadow] = ImVec4();
    // colors[ImGuiCol_FrameBg] = ImVec4();
    // colors[ImGuiCol_FrameBgHovered] = ImVec4();
    // colors[ImGuiCol_FrameBgActive] = ImVec4();
    // colors[ImGuiCol_TitleBg] = ImVec4();
    // colors[ImGuiCol_TitleBgActive] = ImVec4();
    // colors[ImGuiCol_TitleBgCollapsed] = ImVec4();
    // colors[ImGuiCol_MenuBarBg] = ImVec4();
    // colors[ImGuiCol_ScrollbarBg] = ImVec4();
    // colors[ImGuiCol_ScrollbarGrab] = ImVec4();
    // colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4();
    // colors[ImGuiCol_ScrollbarGrabActive] = ImVec4();
    // colors[ImGuiCol_CheckMark] = ImVec4();
    // colors[ImGuiCol_SliderGrab] = ImVec4();
    // colors[ImGuiCol_SliderGrabActive] = ImVec4();
    // colors[ImGuiCol_Button] = ImVec4();
    // colors[ImGuiCol_ButtonHovered] = ImVec4();
    // colors[ImGuiCol_ButtonActive] = ImVec4();
    // colors[ImGuiCol_Header] = ImVec4();
    // colors[ImGuiCol_HeaderHovered] = ImVec4();
    // colors[ImGuiCol_HeaderActive] = ImVec4();
    // colors[ImGuiCol_Separator] = ImVec4();
    // colors[ImGuiCol_SeparatorHovered] = ImVec4();
    // colors[ImGuiCol_SeparatorActive] = ImVec4();
    // colors[ImGuiCol_ResizeGrip] = ImVec4();
    // colors[ImGuiCol_ResizeGripHovered] = ImVec4();
    // colors[ImGuiCol_ResizeGripActive] = ImVec4();
    // colors[ImGuiCol_InputTextCursor] = ImVec4();
    // colors[ImGuiCol_TabHovered] = ImVec4();
    // colors[ImGuiCol_Tab] = ImVec4();
    // colors[ImGuiCol_TabSelected] = ImVec4();
    // colors[ImGuiCol_TabSelectedOverline] = ImVec4();
    // colors[ImGuiCol_TabDimmed] = ImVec4();
    // colors[ImGuiCol_TabDimmedSelected] = ImVec4();
    // colors[ImGuiCol_TabDimmedSelectedOverline] = ImVec4();
    // colors[ImGuiCol_DockingPreview] = ImVec4();
    // colors[ImGuiCol_DockingEmptyBg] = ImVec4();
    // colors[ImGuiCol_PlotLines] = ImVec4();
    // colors[ImGuiCol_PlotLinesHovered] = ImVec4();
    // colors[ImGuiCol_PlotHistogram] = ImVec4();
    // colors[ImGuiCol_PlotHistogramHovered] = ImVec4();
    // colors[ImGuiCol_TableHeaderBg] = ImVec4();
    // colors[ImGuiCol_TableBorderStrong] = ImVec4();
    // colors[ImGuiCol_TableBorderLight] = ImVec4();
    // colors[ImGuiCol_TableRowBg] = ImVec4();
    // colors[ImGuiCol_TableRowBgAlt] = ImVec4();
    // colors[ImGuiCol_TextLink] = ImVec4();
    // colors[ImGuiCol_TextSelectedBg] = ImVec4();
    // colors[ImGuiCol_TreeLines] = ImVec4();
    // colors[ImGuiCol_DragDropTarget] = ImVec4();
    // colors[ImGuiCol_NavCursor] = ImVec4();
    // colors[ImGuiCol_NavWindowingHighlight] = ImVec4();
    // colors[ImGuiCol_NavWindowingDimBg] = ImVec4();
    // colors[ImGuiCol_ModalWindowDimBg] = ImVec4();
}

void Nexus::WindowTheme::UpdateStyle(ImGuiStyle &style)
{
    // Rounding
    style.ChildRounding = 0.f;
    style.FrameRounding = 0.f;
    style.GrabRounding = 0.f;
    style.PopupRounding = 0.f;
    style.ScrollbarRounding = 0.f;
    style.ScrollbarRounding = 0.f;
    style.TabRounding = 0.f;
    style.TreeLinesRounding = 0.f;
    style.WindowRounding = 0.f;
    // Spacing
    // style.ColumnsMinSpacing = 6.f;
    // style.IndentSpacing = 21.f;
    // style.ItemInnerSpacing = ImVec2(4.f, 4.f);
    // style.ItemSpacing = ImVec2(8.f, 4.f);
}